### ISSUE TITLE
Plugin not working. Nothing happens.

### ISSUE THREAD

**Issue by eduard-buta** [anovis/autosizetext#6]
Hi there,
Unfortunately, I cannot get this to work for me. Whatever I try, it just doesn't seem to be doing anything. 

Would love to be able to use this, especially since it's the only brilliant plugin of its type. Let me know if more info is needed from my end to fix this.

**Comment by anovis** [comment]
Thanks for letting me know. I wonder if figma made changes the apis or something. I will look into it today and get back to you.

**Comment by eduard-buta** [comment]
> Thanks for letting me know. I wonder if figma made changes the apis or something. I will look into it today and get back to you.

Appreciate it! Let me know if you need my help with testing anything out, and I'll be glad to do so!
