### ISSUE TITLE
REQ: Linking text fields for scalable resizing of multiple elements

### ISSUE THREAD

**Issue by eduard-buta** [anovis/autosizetext#8]
Hi there,

I would like to suggest a feature. Personally, it would be very helpful for me to be able to link a text field that I'm about to resize, to another text field, allowing for the linked one to scale down in size proportionately with the one I'm running the plugin on. 

How I'd see this done is either:
1. Allowing for the resize of whole components or auto-layouts. When one element gets resized, everything within would resize proportionately too.
2. Some sort of functionality panel allowing to link text layers based on their layer names.

Example: Imagine creating an auto-layout containing a Title and a Paragraph. The whole layout's bounds are clearly defined, so when the paragraph gets too lengthy, I would scale it down to fit within the bounds again through the plugin. But that would end up leaving the title disproportionately large (as font size) against the newly optimized paragraph font size.

**Comment by anovis** [comment]
That is a really interesting idea and I can certainly see the value in that. 

I think 2 might be a little cumbersome for the user (the way the plugin is certainly written) since I don't persist any of the text links so the user would have to link all of the text layers for every change. 

I think option 1 has a lot of potential and will see what I can do around it.

**Comment by eduard-buta** [comment]
> That is a really interesting idea and I can certainly see the value in that.
> 
> I think 2 might be a little cumbersome for the user (the way the plugin is certainly written) since I don't persist any of the text links so the user would have to link all of the text layers for every change.
> 
> I think option 1 has a lot of potential and will see what I can do around it.

Any chance you've begun working on this? Just curious :)

**Comment by anovis** [comment]
@eduard-buta I haven't made much progress. Mostly been thinking how to make `everything within would resize proportionately` work, since the logic i have right now i look at the elements that need to be resized and just expand or shrink until they fit in the bounds each element at a time. 

In the meantime have you tried using the `selection` mode and resizing a selection.  Maybe you can resize the title and then select the child nodes you want resized and see if that works?

**Comment by eduard-buta** [comment]
Unfortunately, that won't work, since you'll still end up running in the same type of problem as I've mentioned above. This is more about making them scale proportionately in relation to each other. So if the title shrinks by 20%, the text follows suit with the same percentage.

The only way I can think of it (with my non-dev background) is to somehow retain the percentage the text shrunk or grew, and then identify every element within the area recursively and apply the same percentage scaling to them also. 

P.S. I've tried making this work by using plugins that allow for variables definition and use within Figma. For example, I tried creating a variable for the paragraph that would represent a certain percentage of the title. So let's say the formula would be 80%*Title-font-size. However, that plugin is limited, since I wasn't able to make one variable dependent on a field value (like a title's font size). It's just the way that plugin was built, unfortunately...

**Comment by anovis** [comment]
gotcha. so one quick thing I should be able to do is calculate and show to the user how much a component shrank by. 

then the user could select items they wish to change by that percentage. 

I will look into automating in one go, but that may be a little complicated to decide which item would be resized first and which ones to recursively resize.

**Comment by eduard-buta** [comment]
I have a general idea of how to do it mathematically, but I may be totally off since I don't know how that would translate into dev. I'll let you know, and maybe it helps. But it definitely implies going through each item twice and storing some data. Plus, I have thought about this from the perspective of shrinking everything down. May need adapting for growing.

1. I would use the plugin as it is right now, but for each item within the field, I would store some sort of a variable containing the original size and the amount it shrunk.
2. I would figure out the max shrinking value. (Let's say the title shrunk from 170pt font size to 138pt, leading to an 18.83% shrinking, and the Paragraph shrunk from 135pt to 126pt leading to a 6.67% shrinking. The max would be 18.83%)
3. I would go through each item in the area again, and compare its shrinking value with the max value. If it's different, it means it has to shrink a little more. We can figure out how much more by using the formula for Total Percentage Changes from Two Sequential Percentage Changes, which is: A + B + A * B. Our A variable is the 6.67% it already shrunk, so 0.0667. Our B variable would be the previously calculated Max - the A variable, so in our example 12.16% or 0.1216. The end result for the formula would be 0.1964, or 19.64%. I would then apply a new font size to this field, based on the stored initial value (which for our paragraph was 135pt) shrunken down by 19.64%.

Haven't done this much math since my early college days, so it was fun lol. I really hope it helps!!

LATER EDIT:

Or even better now that I'm thinking. 

For ONLY shrinking: Go through every item and if all of them need to shrink (and none need to grow) figure out how much each needs to shrink, and store those values. Apply the biggest value then to each one of the items.

For ONLY growing: Go through every item and if all of them need to grow (and none need to shrink) figure out how much each needs to grow, and store those values. Apply the lowest value then to each one of the items.

For a MIX between shrinking and growing: I have no clue how to approach this. Not even sure it makes sense for my particular use-case

P.S. I accidentally closed this issue because I'm a GitHub noob. Apologies.

**Comment by eduard-buta** [comment]
> Haven't done this much math since my early college days, so it was fun lol. I really hope it helps!!

Or even better now that I'm thinking. 

For shrinking: Go through every item and figure out how much they need to shrink and store
